accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('',views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/', views.detail, name='detail'),
    path('delete/', views.delete, name='delete'),
    path('update/',views.update, name='update'),
]

community/urls.py
from django.urls import path
from . import views

app_name ='community'

urlpatterns = [
    path('',views.index, name='index'),
    path('create/',views.create, name='create'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/update/',views.update, name='update'),
    path('<int:pk>/delete/',views.delete, name='delete'),
    path('search/', views.search, name='search'),
]

django_pjt2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls'))
]

movie_reviews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

# model은 필요없다! Django package에 있는 User를 사용할 것이기 때문!

community/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=30)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review_id = models.ForeignKey(Review, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
# from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm

# 그대로 활용하지 못하는 경우는 상속받아서 custom 하기!
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username','first_name','last_name','email']

community/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    title = forms.CharField(
        max_length=100,
        label='Title',
        help_text='Your title must be no more than 100 characters in length',
        widget=forms.TextInput(
            attrs={
                'class':'my_input',
                'placeholder': "Give your review a headline"
            }
        )
    )
    
    movie_title = forms.CharField(
        max_length=30,
        help_text='Please type full movie title',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'ex) Before Sunrise'
            }
        )
    )

    content = forms.CharField(
        label='Content',
        min_length=30,
        help_text='30 Character minimum',
        widget=forms.Textarea(
            attrs={
                'row':5,
                'col':50,
                'placeholder': 'Write your review to help others learn about this movie'
            }
        )
    )

    rank = forms.IntegerField(
        label='Overall rating',
        help_text='Range from 0 to 5',
        widget=forms.NumberInput(
            attrs={
                'type':'range',
                'class': 'custom-range',
                'min': '0',
                'max' :'5',
            }
        )
    )
    class Meta:
        model = Review
        fields = '__all__'    

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, login as auth_login, logout as auth_logout
# from django.contrib.auth.models import User 
# # -> User class는 내부에 정의되어 있으므로 get_user_model method로 호출한다!
from .forms import CustomUserChangeForm
from django.views.decorators.http import require_POST


def index(request):
    User = get_user_model()
    users = User.objects.all()
    content = {
        'users':users
    }
    return render(request,'accounts/index.html', content)

def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('community:index')
    else:
        form = UserCreationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

def detail(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, id=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    if request.method == 'POST':
        # 사용자가 보낸 값 -> form
        form = AuthenticationForm(request, request.POST)
        # 검증
        if form.is_valid():
            # 검증 완료 시 로그인
            auth_login(request, form.get_user())
            
            # [단축평가]
            # or 일 때, 앞에가 False면 뒤에도 검사!
            return redirect(request.GET.get('next') or 'community:index')
    else:    
        form = AuthenticationForm()
    context = {
        'form':form 
    }
    return render(request, 'accounts/signin.html', context)


@login_required
# annotation으로 하지 않고, 조건식으로 직접 작성해도 된다~!
def logout(request):
    auth_logout(request)
    return redirect('community:index')

@require_POST
@login_required
def delete(request):
    request.user.delete()
    return redirect('community:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('community:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context ={
        'form':form
    }
    return render(request, 'accounts/update.html', context)

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Review
from .forms import ReviewForm

# Create your views here.
def index(request):
    reviews = Review.objects.order_by('-pk')
    ranks = Review.objects.raw('select rowid as id, movie_title, avg_rate from (select movie_title, avg(rank) as avg_rate from community_review group by movie_title order by avg_rate desc) LIMIT 3')
    context = {
        'reviews':reviews,
        'ranks': ranks,
    }
    return render(request, 'community/review_list.html', context)

@login_required(redirect_field_name='')
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('community:index')
    else:
        form = ReviewForm()
    context = {
        'form': form
    }
    return render(request, 'community/form.html', context)

def detail(request, pk):
    review = get_object_or_404(Review, id=pk)
    context = {
        'review': review
    }
    return render(request, 'community/review_detail.html', context)

@login_required
def update(request, pk):
    review = get_object_or_404(Review, id=pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review =form.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form':form
    }
    return render(request, 'community/form.html', context)

@login_required
@require_POST
def delete(request, pk):
    review = get_object_or_404(Review, id=pk)
    review.delete()
    return redirect('community:index')

# 영화 제목으로 검색!
def search(request):
    keyword = request.POST.get('keyword')
    reviews = Review.objects.filter(movie_title__icontains=keyword)
    context = {
        'reviews': reviews,
        'keyword': keyword,
    }
    return render(request, 'community/review_list.html', context)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}


<div class="card" style="width: 18rem;">
<h1>{{user.username}}'s Profile</h1>
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <p class="mt-4">First name: <strong>{{user.first_name}}</strong></p>
    <p>Last name: <strong>{{user.last_name}}</strong></p>
    <p>Email: <strong>{{user.email}}</strong></p>
  </div>
</div>

{% if request.user == user %}

    <a href="{% url 'accounts:update' %}">Edit Profile</a>
    <form action="{% url 'accounts:delete'%}" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger"> Delete account</button>
    </form>
{% endif %}
{% endblock  %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}

<h1 class="mb-5">User List</h1>

{% for user in users %}

    <p>#{{user.pk}} - {{user.username}}</p>
    <a href="{% url 'accounts:detail' user.pk %}">See details</a>
    
{% endfor %}

{% endblock  %}

accounts/templates/accounts/signin.html
{% extends 'base.html' %}

{% block content %}

<h1 class="mb-4">Sign In</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success">Log-In</button>
    <a href="{% url 'accounts:signup' %}" class="text-success ml-3">Join us!</a>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h1 class="mb-4">Join Us Today!</h1>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    <button class="btn btn-success">Join</button>
    <a href="{% url 'accounts:login' %}" class="text-success ml-3">Log-In</a>
</form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success">Save the changes</button>
</form>
{% endblock  %}

community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="pb-3">
{% if request.resolver_match.url_name == 'create'%}
    <h3>Write a review</h3>
{% else %}
    <h3>Edit your review</h3>
{% endif %}    

</div>
<form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary" value="Submit">
  <a href="{% url 'community:index' %}" class="btn btn-secondary">Cancel</a>

</form>


{% endblock %}

community/templates/community/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<p class="float-right  mt-3 mb-3 pr-3"><a href="{% url 'community:index' %}"><strong>Back to list</strong></a></p>
<h3 class="mt-3 mb-4">Review # <span id="review_pk">{{review.pk}}</span></h3>

<form action="{% url 'community:update' review.pk %}" method="POST">
{% csrf_token %}
<div class="card text-white bg-dark my-2 w-100">
  
  <div class="card-header">
  <div class="d-flex justify-content-between">
    <div class="d-flex align-items-center">
      <p><h4 id="review_title"> {{review.title}}</h4></p>
      <span class="badge badge-warning mx-2">Rating {{review.rank}}</span> 
    </div>
    <p class="mb-0 pt-1"> 
      <button type="submit" class="btn btn-primary py-1 px-2 ml-2" id="update"><i class='fas fa-pencil-alt' style='font-size:20px;color:white'></i></button> 
      <button type="button" class="btn btn-danger py-1 px-2 " id="delete" data-toggle="modal" data-target="#deleteModal"><i class='far fa-trash-alt' style='font-size:20px;color:white'></i></button>
    </p>
      </div>
  <div class="d-flex justify-content-between align-items-center mt-1">
    <p class="mt-2"> <strong>Movie Title: {{review.movie_title}} </strong></p>
    <div>
      <p class="m-0"> Posted: {{review.created_at|date:'Y-m-d H:i'}}</p>
      <p class="m-0">Last updated: {{review.updated_at|date:'Y-m-d H:i'}}</p>
    </div>
  </div>
  </div>
  <div class="card-body">
    <p class="card-title"><span id="review_content">{{review.content|linebreaksbr}}</span></p>
  </div>
</div>
</form>
<!-- Modal -->
<form action="{% url 'community:delete' review.pk %}" method="POST">
  {% csrf_token %}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header w-100">
        
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center mt-2 mb-3">
      <h4 class="modal-title mb-3" id="exampleModalLabel">Are you sure?</h4>
        Do you really want to delete note? <br>
        This process cannot be undone.
      </div>
      <div class="modal-footer">
      
          <button type="submit" class="btn btn-danger text-white"> Delete</button>
       
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
 </form>


{% endblock %}

community/templates/community/review_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}


{% if ranks %}
<div class="d-flex justify-content-between">
<div>
  <h3 class="mt-3 mb-4 pl-2">Top Rated Movies</h3>
  <p>Sorted by Movie Reviews Rating Descending </p>
</div>
<p><a class="btn btn-outline-primary mt-4 mr-2" href="{% url 'community:create' %}" style='font-size:22px;'>Write a review </a></p>

</div>
  <table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Movie Title</th>
      <th scope="col">Average Rate</th>
    </tr>
  </thead>
  <tbody>
  {% for rank in ranks %}
  <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{rank.movie_title}}</td>
      <td>{{rank.avg_rate}}</td>
  </tr> 
   {% endfor %}
  </tbody>
</table>

{% elif request.resolver_match.url_name != 'search' %}
<div class="text-right">
<p><a class="btn btn-outline-primary mt-4 mr-2" href="{% url 'community:create' %}" style='font-size:22px;'>Write a review </a></p>
</div>


{% endif %}

{% if request.resolver_match.url_name == 'search'%}
<div class="d-flex justify-content-between">
  <h3 class="mt-3 mb-4 pl-2">Search Result for "{{keyword}}"</h3>
  <p class="mt-3 mb-3 pr-3"><a href="{% url 'community:index' %}"><strong>Back to list</strong></a></p>
{% else%}
<div class="pt-3">
  <h3 class="mt-3 mb-4 pl-2">All reviews</h3>
{% endif %}
  
</div>
{% for review in reviews%}

<a class="text-decoration-none" href="{% url 'community:detail' review.pk %}" data-toggle="tooltip" data-placement="top" title="See Details">
<div class="hover card text-white my-2 w-100"  onmouseover="this.style.backgroundColor='#868e96'" onmouseout="this.style.backgroundColor='#343A40'" style="background-color: #343A40">
  <div class="card-header">
    <div class=" d-flex justify-content-between mb-2">
    <span><h5 class="d-inline">{{review.title}}</h5><span class="badge badge-warning mx-2">Rating {{review.rank}}</span></span> <p class="mb-0 pt-1">{{review.created_at|date:'Y-m-d H:i'}}</p>
    </div>
    <p><strong>Movie Title: {{review.movie_title}}</strong></p>
  </div>
  
  <div class="card-body">
    <p class="card-title">{{review.content|truncatechars_html:30}}</p>
  </div>
</div>
<a/>
{% empty %}
<h4 class="mt-4 text-center">No posts yet!</h4>
<p class="text-center ">Jot down any musings or thoughts.</p>

{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Reviews</title>
     <script src='https://kit.fontawesome.com/a076d05399.js'></script>
       <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% bootstrap_css %}
</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light fixed-top bg-dark border border-left-0 border-right-0 border-top-0 border-white py-1 mb-5">
  <a class="navbar-brand" href="/community/"><strong class="text-white">Movie Reviews</strong></a>
  <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-dark "><i class="fas fa-bars" style="color:#fff; font-size:25px;"></i></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarTogglerDemo03">
    <ul class="navbar-nav ml-auto mt-2 mt-md-0 p-2">

    {% if user.is_authenticated %}
      <li class="nav-item dropdown mx-2">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style='font-size:22px;'>Hello, {{user}}!</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <button class="dropdown-item"  style='font-size:22px;' data-toggle="modal" data-target="#profileModal">Profile</button>
          <button class="dropdown-item"  style='font-size:22px;'><a href="{% url 'accounts:logout' %}" class="text-decoration-none">Log-out</a></button>
        </div>
      </li> 
       <li class="nav-item mx-2">
        <a class="nav-link text-white" href="{% url 'community:create' %}" style='font-size:22px;'>Write a Review </a>
      </li>
      {% else %}
      <li class="nav-item active mx-2">
        <a class="nav-link text-white" href="{% url 'accounts:login' %}" style='font-size:22px;'>Log-in<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active mx-2">
        <a class="nav-link text-white" href="{% url 'accounts:signup' %}" style='font-size:22px;'>Join<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      <li class="nav-item active mx-2">
        <a class="nav-link text-white" href="{% url 'community:index' %}" style='font-size:22px;'>Reviews<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
  <form class="form-inline" action="{% url 'community:search' %}" method="POST">
  {% csrf_token %}
    <input class="form-control mr-sm-2" name="keyword"type="search" placeholder="Search movies" aria-label="Search">
    <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>



<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLongTitle">{{user.username}}'s Profile</h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="mt-4">First name: <strong>{{user.first_name}}</strong></p>
        <p>Last name: <strong>{{user.last_name}}</strong></p>
        <p>Email: <strong>{{user.email}}</strong></p>
      </div>
      <div class="modal-footer">
         {% if request.user == user %}
          <a href="{% url 'accounts:update' %}" class="btn btn-warning text-white">Edit Profile</a>
          <form action="{% url 'accounts:delete'%}" method="POST">
            {% csrf_token %}
          <button class="btn btn-danger"> Delete account</button>
          </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="card w-75 m-auto py-3">
  <div class="card-header text-center mt-5 bg-light">
    <h2 class="pt-5 pb-5">Movie reviews and ratings</h2>
  </div>
  <div class="card-body">

  {% block content %}

  {% endblock %}

    </div>
</div>


<footer>
<div class="footer-copyright text-center py-3 ">© 2020 Copyright:
    <a href="https://github.com/chloe-codes1" class="text-decoration-none"> <i class="fab fa-github ml-1"></i> chloe-codes1</a>
  </div>
</footer>
    
    {% bootstrap_javascript jquery='full' %}
</body>
</html>